// ============================================================
// STYLESWAP MOCK DATA
// ============================================================

export const INITIAL_USERS = [
    // Admin
    {
        id: 'admin-001',
        name: 'Alex Morgan',
        email: 'admin@styleswap.com',
        password: 'admin123',
        role: 'Admin',
        shopName: null,
        createdAt: '2024-01-01T00:00:00.000Z',
        status: 'active',
        avatar: null,
    },
    // Sub-Admins / Vendors
    {
        id: 'vendor-001',
        name: 'Sophia Elegance',
        email: 'elegance@styleswap.com',
        password: 'vendor123',
        role: 'Sub-Admin',
        shopName: 'Elegance Rentals',
        createdAt: '2024-01-15T00:00:00.000Z',
        status: 'active',
        avatar: null,
        shopAddress: '12 Fashion Lane, Bandra West, Mumbai, Maharashtra 400050',
        shopNumber: 'SHOP/MH/2024/001',
        mobileNumber: '+91 98765 43210',
        salesHandlerMobile: '+91 91234 56789',
        gstNumber: '27AABCE1234F1Z5',
        onboardedAt: '2024-01-16T00:00:00.000Z',
    },
    {
        id: 'vendor-002',
        name: 'Marcus Formal',
        email: 'formal@styleswap.com',
        password: 'vendor123',
        role: 'Sub-Admin',
        shopName: 'Formal Affair',
        createdAt: '2024-02-01T00:00:00.000Z',
        status: 'active',
        avatar: null,
        shopAddress: '45 Business Hub, Connaught Place, New Delhi 110001',
        shopNumber: 'SHOP/DL/2024/002',
        mobileNumber: '+91 98001 23456',
        salesHandlerMobile: '+91 90001 23456',
        gstNumber: '07AABCF5678G1Z3',
        onboardedAt: '2024-02-02T00:00:00.000Z',
    },
    {
        id: 'vendor-003',
        name: 'Priya Accessories',
        email: 'accessory@styleswap.com',
        password: 'vendor123',
        role: 'Sub-Admin',
        shopName: 'Accessory Avenue',
        createdAt: '2024-02-15T00:00:00.000Z',
        status: 'active',
        avatar: null,
        shopAddress: '78 MG Road, Indiranagar, Bengaluru, Karnataka 560038',
        shopNumber: 'SHOP/KA/2024/003',
        mobileNumber: '+91 97654 32109',
        salesHandlerMobile: '+91 89012 34567',
        gstNumber: null,
        onboardedAt: '2024-02-16T00:00:00.000Z',
    },
    // Regular Users / Customers
    {
        id: 'user-001',
        name: 'James Wilson',
        email: 'customer@styleswap.com',
        password: 'user123',
        role: 'User',
        shopName: null,
        createdAt: '2024-03-01T00:00:00.000Z',
        status: 'active',
        avatar: null,
    },
    {
        id: 'user-002',
        name: 'Emma Thompson',
        email: 'emma@example.com',
        password: 'user123',
        role: 'User',
        shopName: null,
        createdAt: '2024-03-10T00:00:00.000Z',
        status: 'active',
        avatar: null,
    },
    {
        id: 'user-003',
        name: 'Raj Patel',
        email: 'raj@example.com',
        password: 'user123',
        role: 'User',
        shopName: null,
        createdAt: '2024-03-20T00:00:00.000Z',
        status: 'active',
        avatar: null,
    },
    {
        id: 'user-004',
        name: 'Lily Chen',
        email: 'lily@example.com',
        password: 'user123',
        role: 'User',
        shopName: null,
        createdAt: '2024-04-01T00:00:00.000Z',
        status: 'active',
        avatar: null,
    },
    {
        id: 'user-005',
        name: 'Carlos Rivera',
        email: 'carlos@example.com',
        password: 'user123',
        role: 'User',
        shopName: null,
        createdAt: '2024-04-15T00:00:00.000Z',
        status: 'active',
        avatar: null,
    },
];

export const INITIAL_PRODUCTS = [
    // =====================
    // ELEGANCE RENTALS (vendor-001) - Wedding Attire & Formal Wear
    // =====================
    {
        id: 'prod-001',
        subAdminId: 'vendor-001',
        shopName: 'Elegance Rentals',
        name: 'Midnight Blue Tuxedo',
        category: 'Wedding Attire',
        pricePerDay: 75,
        securityDeposit: 150,
        description: 'Elegant 3-piece midnight blue tuxedo with satin lapels. Perfect for weddings, galas, and black-tie events. Includes jacket, trousers, and waistcoat.',
        images: [
            'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600',
            'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600',
        ],
        stockQuantity: 5,
        availableQuantity: 4,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        createdAt: '2024-02-01T00:00:00.000Z',
        ratings: 4.8,
    },
    {
        id: 'prod-002',
        subAdminId: 'vendor-001',
        shopName: 'Elegance Rentals',
        name: 'Ivory Wedding Gown',
        category: 'Wedding Attire',
        pricePerDay: 120,
        securityDeposit: 300,
        description: 'Stunning A-line ivory wedding gown with lace bodice and flowing chiffon skirt. Features a 2-meter train and intricate beadwork.',
        images: [
            'https://images.unsplash.com/photo-1519657337289-077653f724ed?w=600',
            'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=600',
        ],
        stockQuantity: 3,
        availableQuantity: 2,
        sizes: ['XS', 'S', 'M', 'L'],
        createdAt: '2024-02-05T00:00:00.000Z',
        ratings: 4.9,
    },
    {
        id: 'prod-003',
        subAdminId: 'vendor-001',
        shopName: 'Elegance Rentals',
        name: 'Classic Black Tuxedo',
        category: 'Wedding Attire',
        pricePerDay: 65,
        securityDeposit: 130,
        description: 'Timeless classic black tuxedo with peak lapels. A wardrobe staple for any formal occasion. Comes with matching bow tie.',
        images: [
            'https://images.unsplash.com/photo-1598808503746-f34c53b9323e?w=600',
            'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=600',
        ],
        stockQuantity: 8,
        availableQuantity: 7,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        createdAt: '2024-02-10T00:00:00.000Z',
        ratings: 4.6,
    },
    {
        id: 'prod-004',
        subAdminId: 'vendor-001',
        shopName: 'Elegance Rentals',
        name: 'Blush Bridesmaid Dress',
        category: 'Wedding Attire',
        pricePerDay: 45,
        securityDeposit: 90,
        description: 'Elegant floor-length blush pink bridesmaid dress with ruched bodice and chiffon skirt. Perfect for spring and summer weddings.',
        images: [
            'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600',
            'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600',
        ],
        stockQuantity: 6,
        availableQuantity: 5,
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        createdAt: '2024-02-15T00:00:00.000Z',
        ratings: 4.7,
    },
    {
        id: 'prod-005',
        subAdminId: 'vendor-001',
        shopName: 'Elegance Rentals',
        name: 'Champagne Evening Gown',
        category: 'Wedding Attire',
        pricePerDay: 95,
        securityDeposit: 200,
        description: 'Breathtaking champagne-colored evening gown with sequined bodice and flowing skirt. Perfect for mother of the bride or gala events.',
        images: [
            'https://images.unsplash.com/photo-1566479179817-c0a3e3e4e0a8?w=600',
            'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600',
        ],
        stockQuantity: 4,
        availableQuantity: 3,
        sizes: ['XS', 'S', 'M', 'L'],
        createdAt: '2024-02-20T00:00:00.000Z',
        ratings: 4.5,
    },
    {
        id: 'prod-006',
        subAdminId: 'vendor-001',
        shopName: 'Elegance Rentals',
        name: 'Navy Blue Suit',
        category: 'Wedding Attire',
        pricePerDay: 55,
        securityDeposit: 110,
        description: 'Sharp navy blue 2-piece suit perfect for wedding guests and groomsmen. Slim fit with notch lapels.',
        images: [
            'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600',
            'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600',
        ],
        stockQuantity: 7,
        availableQuantity: 6,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        createdAt: '2024-02-25T00:00:00.000Z',
        ratings: 4.4,
    },
    {
        id: 'prod-007',
        subAdminId: 'vendor-001',
        shopName: 'Elegance Rentals',
        name: 'Emerald Cocktail Dress',
        category: 'Wedding Attire',
        pricePerDay: 50,
        securityDeposit: 100,
        description: 'Stunning emerald green cocktail dress with wrap silhouette. Perfect for wedding receptions and cocktail parties.',
        images: [
            'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600',
            'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600',
        ],
        stockQuantity: 5,
        availableQuantity: 4,
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        createdAt: '2024-03-01T00:00:00.000Z',
        ratings: 4.6,
    },

    // =====================
    // FORMAL AFFAIR (vendor-002) - Blazers & Business Attire
    // =====================
    {
        id: 'prod-008',
        subAdminId: 'vendor-002',
        shopName: 'Formal Affair',
        name: 'Charcoal Power Blazer',
        category: 'Blazers',
        pricePerDay: 40,
        securityDeposit: 80,
        description: 'Sharp charcoal grey blazer with structured shoulders. Perfect for business meetings, conferences, and professional events.',
        images: [
            'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=600',
            'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600',
        ],
        stockQuantity: 10,
        availableQuantity: 8,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        createdAt: '2024-02-01T00:00:00.000Z',
        ratings: 4.5,
    },
    {
        id: 'prod-009',
        subAdminId: 'vendor-002',
        shopName: 'Formal Affair',
        name: 'Camel Double-Breasted Blazer',
        category: 'Blazers',
        pricePerDay: 45,
        securityDeposit: 90,
        description: 'Luxurious camel-colored double-breasted blazer. A statement piece for fashion-forward professionals.',
        images: [
            'https://images.unsplash.com/photo-1598808503746-f34c53b9323e?w=600',
            'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600',
        ],
        stockQuantity: 6,
        availableQuantity: 5,
        sizes: ['S', 'M', 'L', 'XL'],
        createdAt: '2024-02-08T00:00:00.000Z',
        ratings: 4.7,
    },
    {
        id: 'prod-010',
        subAdminId: 'vendor-002',
        shopName: 'Formal Affair',
        name: 'Pinstripe Business Suit',
        category: 'Blazers',
        pricePerDay: 60,
        securityDeposit: 120,
        description: 'Classic navy pinstripe 3-piece business suit. Exudes authority and sophistication for important meetings.',
        images: [
            'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600',
            'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600',
        ],
        stockQuantity: 5,
        availableQuantity: 4,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        createdAt: '2024-02-15T00:00:00.000Z',
        ratings: 4.8,
    },
    {
        id: 'prod-011',
        subAdminId: 'vendor-002',
        shopName: 'Formal Affair',
        name: 'Velvet Dinner Jacket',
        category: 'Blazers',
        pricePerDay: 55,
        securityDeposit: 110,
        description: 'Luxurious midnight blue velvet dinner jacket. Perfect for formal dinners, award ceremonies, and upscale events.',
        images: [
            'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600',
            'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=600',
        ],
        stockQuantity: 4,
        availableQuantity: 3,
        sizes: ['S', 'M', 'L', 'XL'],
        createdAt: '2024-02-22T00:00:00.000Z',
        ratings: 4.6,
    },
    {
        id: 'prod-012',
        subAdminId: 'vendor-002',
        shopName: 'Formal Affair',
        name: 'White Linen Blazer',
        category: 'Blazers',
        pricePerDay: 35,
        securityDeposit: 70,
        description: 'Crisp white linen blazer for summer events. Lightweight and breathable, perfect for outdoor weddings and garden parties.',
        images: [
            'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600',
            'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600',
        ],
        stockQuantity: 8,
        availableQuantity: 7,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        createdAt: '2024-03-01T00:00:00.000Z',
        ratings: 4.3,
    },
    {
        id: 'prod-013',
        subAdminId: 'vendor-002',
        shopName: 'Formal Affair',
        name: 'Burgundy Sport Coat',
        category: 'Blazers',
        pricePerDay: 38,
        securityDeposit: 75,
        description: 'Rich burgundy sport coat with subtle texture. Versatile piece that pairs well with dress trousers or dark jeans.',
        images: [
            'https://images.unsplash.com/photo-1598808503746-f34c53b9323e?w=600',
            'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600',
        ],
        stockQuantity: 6,
        availableQuantity: 5,
        sizes: ['S', 'M', 'L', 'XL'],
        createdAt: '2024-03-08T00:00:00.000Z',
        ratings: 4.4,
    },
    {
        id: 'prod-014',
        subAdminId: 'vendor-002',
        shopName: 'Formal Affair',
        name: 'Tweed Heritage Blazer',
        category: 'Blazers',
        pricePerDay: 42,
        securityDeposit: 85,
        description: 'Classic British tweed blazer in herringbone pattern. Perfect for autumn events, races, and country-style occasions.',
        images: [
            'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=600',
            'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600',
        ],
        stockQuantity: 5,
        availableQuantity: 4,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        createdAt: '2024-03-15T00:00:00.000Z',
        ratings: 4.5,
    },

    // =====================
    // ACCESSORY AVENUE (vendor-003) - Shoes & Accessories
    // =====================
    {
        id: 'prod-015',
        subAdminId: 'vendor-003',
        shopName: 'Accessory Avenue',
        name: 'Classic Oxford Dress Shoes',
        category: 'Shoes',
        pricePerDay: 25,
        securityDeposit: 50,
        description: 'Timeless black Oxford dress shoes in genuine leather. Perfectly polished for formal occasions.',
        images: [
            'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
            'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600',
        ],
        stockQuantity: 10,
        availableQuantity: 8,
        sizes: ['7', '8', '9', '10', '11', '12'],
        createdAt: '2024-02-01T00:00:00.000Z',
        ratings: 4.6,
    },
    {
        id: 'prod-016',
        subAdminId: 'vendor-003',
        shopName: 'Accessory Avenue',
        name: 'Strappy Gold Heels',
        category: 'Shoes',
        pricePerDay: 30,
        securityDeposit: 60,
        description: 'Glamorous strappy gold heels with 4-inch stiletto. Perfect for weddings, galas, and special occasions.',
        images: [
            'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600',
            'https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=600',
        ],
        stockQuantity: 8,
        availableQuantity: 6,
        sizes: ['5', '6', '7', '8', '9'],
        createdAt: '2024-02-08T00:00:00.000Z',
        ratings: 4.7,
    },
    {
        id: 'prod-017',
        subAdminId: 'vendor-003',
        shopName: 'Accessory Avenue',
        name: 'Luxury Leather Belt Collection',
        category: 'Accessories',
        pricePerDay: 10,
        securityDeposit: 20,
        description: 'Set of 3 premium leather belts in black, brown, and tan. Gold and silver buckle options available.',
        images: [
            'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600',
            'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600',
        ],
        stockQuantity: 15,
        availableQuantity: 12,
        sizes: ['S', 'M', 'L', 'XL'],
        createdAt: '2024-02-15T00:00:00.000Z',
        ratings: 4.4,
    },
    {
        id: 'prod-018',
        subAdminId: 'vendor-003',
        shopName: 'Accessory Avenue',
        name: 'Diamond Stud Earrings',
        category: 'Accessories',
        pricePerDay: 35,
        securityDeposit: 200,
        description: 'Elegant diamond stud earrings (0.5 carat each) in 18k white gold setting. Perfect for weddings and formal events.',
        images: [
            'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600',
            'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600',
        ],
        stockQuantity: 5,
        availableQuantity: 4,
        sizes: ['One Size'],
        createdAt: '2024-02-22T00:00:00.000Z',
        ratings: 4.9,
    },
    {
        id: 'prod-019',
        subAdminId: 'vendor-003',
        shopName: 'Accessory Avenue',
        name: 'Designer Clutch Bag',
        category: 'Accessories',
        pricePerDay: 20,
        securityDeposit: 80,
        description: 'Elegant satin clutch bag with gold chain strap. Available in ivory, black, and champagne. Perfect for evening events.',
        images: [
            'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
            'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600',
        ],
        stockQuantity: 8,
        availableQuantity: 7,
        sizes: ['One Size'],
        createdAt: '2024-03-01T00:00:00.000Z',
        ratings: 4.5,
    },
    {
        id: 'prod-020',
        subAdminId: 'vendor-003',
        shopName: 'Accessory Avenue',
        name: 'Silk Tie Collection',
        category: 'Accessories',
        pricePerDay: 8,
        securityDeposit: 15,
        description: 'Premium silk tie collection featuring 5 classic patterns: solid navy, burgundy stripe, silver paisley, black herringbone, and gold geometric.',
        images: [
            'https://images.unsplash.com/photo-1589756823695-278bc923f962?w=600',
            'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600',
        ],
        stockQuantity: 20,
        availableQuantity: 18,
        sizes: ['One Size'],
        createdAt: '2024-03-08T00:00:00.000Z',
        ratings: 4.3,
    },
    {
        id: 'prod-021',
        subAdminId: 'vendor-003',
        shopName: 'Accessory Avenue',
        name: 'Ankle Strap Heels',
        category: 'Shoes',
        pricePerDay: 28,
        securityDeposit: 55,
        description: 'Elegant black ankle strap heels with 3-inch block heel. Comfortable for all-day wear at events.',
        images: [
            'https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=600',
            'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600',
        ],
        stockQuantity: 7,
        availableQuantity: 6,
        sizes: ['5', '6', '7', '8', '9', '10'],
        createdAt: '2024-03-15T00:00:00.000Z',
        ratings: 4.6,
    },
    {
        id: 'prod-022',
        subAdminId: 'vendor-003',
        shopName: 'Accessory Avenue',
        name: 'Gold Cufflinks Set',
        category: 'Accessories',
        pricePerDay: 12,
        securityDeposit: 40,
        description: 'Sophisticated gold cufflinks set with 4 pairs: plain gold, monogram, navy enamel, and mother of pearl.',
        images: [
            'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600',
            'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600',
        ],
        stockQuantity: 12,
        availableQuantity: 10,
        sizes: ['One Size'],
        createdAt: '2024-03-22T00:00:00.000Z',
        ratings: 4.7,
    },
    {
        id: 'prod-023',
        subAdminId: 'vendor-003',
        shopName: 'Accessory Avenue',
        name: 'Brogue Dress Shoes',
        category: 'Shoes',
        pricePerDay: 22,
        securityDeposit: 45,
        description: 'Classic tan brogue dress shoes with wingtip detailing. Versatile for both formal and smart-casual occasions.',
        images: [
            'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600',
            'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
        ],
        stockQuantity: 9,
        availableQuantity: 8,
        sizes: ['7', '8', '9', '10', '11', '12'],
        createdAt: '2024-03-29T00:00:00.000Z',
        ratings: 4.5,
    },
];

// Mock orders for analytics
export const INITIAL_ORDERS = [
    {
        orderId: 'order-001',
        customerId: 'user-001',
        customerName: 'James Wilson',
        items: [
            {
                productId: 'prod-001',
                productName: 'Midnight Blue Tuxedo',
                vendorId: 'vendor-001',
                vendorShopName: 'Elegance Rentals',
                quantity: 1,
                size: 'L',
                rentalStartDate: '2024-11-15',
                rentalEndDate: '2024-11-19',
                rentalDays: 4,
                subtotal: 300,
                deposit: 150,
            },
        ],
        totalAmount: 300,
        totalDeposit: 150,
        orderDate: '2024-11-10T00:00:00.000Z',
        status: 'Returned',
        shippingAddress: {
            fullName: 'James Wilson',
            phone: '555-0101',
            address1: '123 Main St',
            city: 'New York',
            state: 'NY',
            zip: '10001',
            country: 'USA',
        },
        paymentMethod: 'Credit Card',
    },
    {
        orderId: 'order-002',
        customerId: 'user-002',
        customerName: 'Emma Thompson',
        items: [
            {
                productId: 'prod-002',
                productName: 'Ivory Wedding Gown',
                vendorId: 'vendor-001',
                vendorShopName: 'Elegance Rentals',
                quantity: 1,
                size: 'S',
                rentalStartDate: '2024-12-20',
                rentalEndDate: '2024-12-23',
                rentalDays: 3,
                subtotal: 360,
                deposit: 300,
            },
            {
                productId: 'prod-016',
                productName: 'Strappy Gold Heels',
                vendorId: 'vendor-003',
                vendorShopName: 'Accessory Avenue',
                quantity: 1,
                size: '7',
                rentalStartDate: '2024-12-20',
                rentalEndDate: '2024-12-23',
                rentalDays: 3,
                subtotal: 90,
                deposit: 60,
            },
        ],
        totalAmount: 450,
        totalDeposit: 360,
        orderDate: '2024-12-15T00:00:00.000Z',
        status: 'Returned',
        shippingAddress: {
            fullName: 'Emma Thompson',
            phone: '555-0102',
            address1: '456 Oak Ave',
            city: 'Los Angeles',
            state: 'CA',
            zip: '90001',
            country: 'USA',
        },
        paymentMethod: 'PayPal',
    },
    {
        orderId: 'order-003',
        customerId: 'user-001',
        customerName: 'James Wilson',
        items: [
            {
                productId: 'prod-008',
                productName: 'Charcoal Power Blazer',
                vendorId: 'vendor-002',
                vendorShopName: 'Formal Affair',
                quantity: 1,
                size: 'M',
                rentalStartDate: '2025-01-10',
                rentalEndDate: '2025-01-13',
                rentalDays: 3,
                subtotal: 120,
                deposit: 80,
            },
        ],
        totalAmount: 120,
        totalDeposit: 80,
        orderDate: '2025-01-05T00:00:00.000Z',
        status: 'Returned',
        shippingAddress: {
            fullName: 'James Wilson',
            phone: '555-0101',
            address1: '123 Main St',
            city: 'New York',
            state: 'NY',
            zip: '10001',
            country: 'USA',
        },
        paymentMethod: 'Credit Card',
    },
    {
        orderId: 'order-004',
        customerId: 'user-003',
        customerName: 'Raj Patel',
        items: [
            {
                productId: 'prod-010',
                productName: 'Pinstripe Business Suit',
                vendorId: 'vendor-002',
                vendorShopName: 'Formal Affair',
                quantity: 1,
                size: 'L',
                rentalStartDate: '2026-02-20',
                rentalEndDate: '2026-02-25',
                rentalDays: 5,
                subtotal: 300,
                deposit: 120,
            },
            {
                productId: 'prod-015',
                productName: 'Classic Oxford Dress Shoes',
                vendorId: 'vendor-003',
                vendorShopName: 'Accessory Avenue',
                quantity: 1,
                size: '10',
                rentalStartDate: '2026-02-20',
                rentalEndDate: '2026-02-25',
                rentalDays: 5,
                subtotal: 125,
                deposit: 50,
            },
        ],
        totalAmount: 425,
        totalDeposit: 170,
        orderDate: '2026-02-15T00:00:00.000Z',
        status: 'Active',
        shippingAddress: {
            fullName: 'Raj Patel',
            phone: '555-0103',
            address1: '789 Elm St',
            city: 'Chicago',
            state: 'IL',
            zip: '60601',
            country: 'USA',
        },
        paymentMethod: 'Credit Card',
    },
    {
        orderId: 'order-005',
        customerId: 'user-001',
        customerName: 'James Wilson',
        items: [
            {
                productId: 'prod-003',
                productName: 'Classic Black Tuxedo',
                vendorId: 'vendor-001',
                vendorShopName: 'Elegance Rentals',
                quantity: 1,
                size: 'M',
                rentalStartDate: '2026-02-18',
                rentalEndDate: '2026-02-22',
                rentalDays: 4,
                subtotal: 260,
                deposit: 130,
            },
        ],
        totalAmount: 260,
        totalDeposit: 130,
        orderDate: '2026-02-14T00:00:00.000Z',
        status: 'Active',
        shippingAddress: {
            fullName: 'James Wilson',
            phone: '555-0101',
            address1: '123 Main St',
            city: 'New York',
            state: 'NY',
            zip: '10001',
            country: 'USA',
        },
        paymentMethod: 'Cash on Delivery',
    },
];

// Initialize localStorage with mock data.
// Uses a version key — if the version doesn't match, all data is re-seeded.
// Bump MOCK_DATA_VERSION whenever you want to force a fresh reset.
const MOCK_DATA_VERSION = 'v2';

export function initializeMockData() {
    const storedVersion = localStorage.getItem('styleswap_data_version');

    if (storedVersion !== MOCK_DATA_VERSION) {
        // Clear everything and re-seed
        localStorage.removeItem('styleswap_users');
        localStorage.removeItem('styleswap_products');
        localStorage.removeItem('styleswap_orders');
        localStorage.removeItem('styleswap_currentUser');
        // Clear all per-user carts
        Object.keys(localStorage)
            .filter(k => k.startsWith('styleswap_cart_'))
            .forEach(k => localStorage.removeItem(k));

        localStorage.setItem('styleswap_users', JSON.stringify(INITIAL_USERS));
        localStorage.setItem('styleswap_products', JSON.stringify(INITIAL_PRODUCTS));
        localStorage.setItem('styleswap_orders', JSON.stringify(INITIAL_ORDERS));
        localStorage.setItem('styleswap_data_version', MOCK_DATA_VERSION);
    }
}
